# Generated by Django 3.2.2 on 2021-06-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
