# Generated by Django 3.2.2 on 2021-06-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_visited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visited',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='visited',
            name='last_name',
        ),
        migrations.AddField(
            model_name='visited',
            name='product',
            field=models.IntegerField(null=True),
        ),
    ]
